### ISSUE TITLE
use with bitbucket instead of github

### ISSUE THREAD

**Issue by tjaartvdwalt** [syohex/emacs-helm-open-github#11]
I was trying to open a commit but I got a 404 error. Eventually I realised it was because my remote is a bitbucket repository, not a github one.

How easy do you think it will be to accomodate bitbucket? 
Would you be willing to incorporate it into the package if I worked on this and send you a pull request?

**Comment by syohex** [comment]
> How easy do you think it will be to accomodate bitbucket?

No way.
This package has heavy dependence on github and many code cannot be used for bitbacket.

I suppose it is better to create another package like `helm-open-bitbacket` rather than
customizing this package.
