### ISSUE TITLE
Get all issues of a repo, even the old.

### ISSUE THREAD

**Issue by thierryvolpiatto** [syohex/emacs-helm-open-github#7]
Hi, is it possible to browse all the issues, even the old ones ?

Thanks.

**Comment by syohex** [comment]
No.

We need to set parameter for getting all issues, however we cannot pass parameters
to `gh.el` API.

See
https://developer.github.com/v3/issues/#parameters

Github issues api of `gh.el` is as below.
```lisp
(defmethod gh-issues-issue-list ((api gh-issues-api) user repo)
  (gh-api-authenticated-request
   api (gh-object-list-reader (oref api issue-cls)) "GET"
   (format "/repos/%s/%s/issues" user repo)))
```

This method does not take `parameters` argument.

If its definition is like following code, we can get all issues when `params` is `'(("state" . "all"))`.

```lisp
(defmethod gh-issues-issue-list ((api gh-issues-api) user repo &optional params)
  (gh-api-authenticated-request
   api (gh-object-list-reader (oref api issue-cls)) "GET"
   (format "/repos/%s/%s/issues" user repo)
   nil params))
```

(I maybe mistake, I don't understand CLOS(`eieio`) well).
