### ISSUE TITLE
Invalid gh version ?

### ISSUE THREAD

**Issue by nlamirault** [syohex/emacs-helm-open-github#9]
I can't install your package (0.12.0) because it's depends on gh 1.0 : 

```lisp
;; Package-Requires: ((helm "1.0") (gh "1.0") (cl-lib "0.5"))
```

but according to git repository [1] and Melpa stable [2], last version of gh is 0.9.2

[1]: https://github.com/sigma/gh.el/tags
[2]: http://stable.melpa.org/#/gh

**Comment by syohex** [comment]
Thanks for reporting issue.
I have fixed at #10.
